### ISSUE TITLE
Copay Multi-Sig: To Address is not shown in Payment Proposals

### ISSUE THREAD

**Issue by lclc** [digitalbitbox/dbb-app#154]
![dbb1](https://cloud.githubusercontent.com/assets/1846033/14290593/e1c37bba-fb5f-11e5-8dc0-8da4b953bc6d.png)

The address should be 1FiroDvTrXmU8P8KpPqEVTo5byaVkg9X9o

Running the latest release (not master).

**Comment by douglasbakkum** [comment]
fixed by #193
