### ISSUE TITLE
Set Passwort: Button not clickable

### ISSUE THREAD

**Issue by lclc** [digitalbitbox/dbb-app#157]
On my Arch LInux using the latest release:

I enter the new password twice, but clicking the button doesn't do anything. It works when I press enter - so no big problem.

**Comment by douglasbakkum** [comment]
Hmm. Might have gotten fixed along the way of overhauling the app, for example in #170. I couldn't reproduce and the code is clear about what the button click (should) do: https://github.com/digitalbitbox/dbb-app/blob/master/src/qt/modalview.cpp#L25

I'll close for now, but please reopen if the problem persists. Thanks! 

(note that the current dbb-app code is not backward compatible with current release of the MCU firmware, so we will need to update your device before you could test)
