### ISSUE TITLE
Copay Multi-Signature: Broadcast fails

### ISSUE THREAD

**Issue by lclc** [digitalbitbox/dbb-app#158]
Using the latest dbb-app master.

The error in the pop-up alert is:
"Could not post signatures"
Then it's stuck at the black screen saying "Broadcast Transaction"

The output of the dbb-app (from start until black screen):
http://pastebin.com/tuCjnjv0

Fresh update device, resetted, DBB v0.2.1-v0.2.1, Device version v1.3.2

**Comment by jonasschnelli** [comment]
Should be fixed by now.
