### ISSUE TITLE
udev rules don't seem to work on Ubuntu 16.04

### ISSUE THREAD

**Issue by laanwj** [digitalbitbox/dbb-app#160]
I'm not good at interpreting or debugging udev rules, but for some reason those given on https://digitalbitbox.com/start_linux don't seem to work. After pasting the rules 

```
SUBSYSTEM=="usb", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="dbb", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2402"
```

into the right directory and rebooting, nothing changes, the user cannot access the device but root can.

What did work for me is the brute-force way that I usually use to give users (in the `plugdev` group) access to a device:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="2402", GROUP="plugdev", MODE="0664"
```

**Comment by jonasschnelli** [comment]
@laanwj: thanks!
@douglasbakkum: We should probably update the website with that (I'm not really familiar with USB permissions on Linux)?

**Comment by douglasbakkum** [comment]
Thanks a lot for testing!

I added your udev rule to the start_linux page. I will keep the current udev rule on the page also, as there are some advantages to using it including I have read that the `plugdev` group is not necessarily available in all linux distributions.

**Comment by laanwj** [comment]
Yes, I don't actually know why the other rule doesn't work. "uaccess" seems more general.
I suppose it indeed differs per distro.

**Comment by douglasbakkum** [comment]
Guessing that uaccess is a newer feature and somehow didn't propagate to the distro you are using. I'll close this issue - thanks!
