### ISSUE TITLE
Starting dbb-app multiple times results in "No device connected"

### ISSUE THREAD

**Issue by laanwj** [digitalbitbox/dbb-app#163]
I just had a mildly confusing experience - it looked like the bitbox was no longer being detected by either dbb-cli or dbb-app.

However it turned out that the application was already running in the background!

Wouldn't know how to do this with hidapi, but it'd be nice to have a different error message when the device is already 'claimed'.

**Comment by douglasbakkum** [comment]
btw, thanks for reporting!
