### ISSUE TITLE
dbb-app crash on unlock wallet in osx 10.12.4

### ISSUE THREAD

**Issue by cdelargy** [digitalbitbox/dbb-app#240]
Unable to unlock device for a 2 of 2 multisig wallet with open payment proposal (from copay mobile wallet). High priority, coins stuck.

Error thrown appears to be
>JSON integer out of range

Process:               dbb-app [5646]
Path:                  /Volumes/VOLUME/*/DigitalBitbox 2.app/Contents/MacOS/dbb-app
Identifier:            com.shiftdevices.digitalbitboxapp
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           dbb-app [5646]
User ID:               501

Date/Time:             2017-03-09 11:26:57.335 -0500
OS Version:            Mac OS X 10.12.4 (16E183b)
Report Version:        12
Anonymous UUID:        ***

Sleep/Wake UUID:       ***

Time Awake Since Boot: 61000 seconds
Time Since Wake:       2900 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
terminating with uncaught exception of type std::runtime_error: JSON integer out of range

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffb3111d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffb31ff787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffb3077420 abort + 129
3   libc++abi.dylib               	0x00007fffb1bcd84a abort_message + 266
4   libc++abi.dylib               	0x00007fffb1bf2c37 default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fffb2700713 _objc_terminate() + 124
6   libc++abi.dylib               	0x00007fffb1befd69 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fffb1bef9f2 __cxa_rethrow + 99
8   libobjc.A.dylib               	0x00007fffb26fe94a objc_exception_rethrow + 40
9   com.apple.CoreFoundation      	0x00007fff9d87624b CFRunLoopRunSpecific + 555
10  com.apple.HIToolbox           	0x00007fff9cdd7ebc RunCurrentEventLoopInMode + 240
11  com.apple.HIToolbox           	0x00007fff9cdd7cf1 ReceiveNextEventCommon + 432
12  com.apple.HIToolbox           	0x00007fff9cdd7b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
13  com.apple.AppKit              	0x00007fff9b372e24 _DPSNextEvent + 1120
14  com.apple.AppKit              	0x00007fff9baee85e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
15  com.apple.AppKit              	0x00007fff9b3677ab -[NSApplication run] + 926
16  com.shiftdevices.digitalbitboxapp	0x0000000106f2ffc0 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2480
17  com.shiftdevices.digitalbitboxapp	0x000000010777e2ad QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 397
18  com.shiftdevices.digitalbitboxapp	0x0000000107781585 QCoreApplication::exec() + 341
19  com.shiftdevices.digitalbitboxapp	0x0000000106d807f4 main + 1236
20  com.shiftdevices.digitalbitboxapp	0x0000000106d7fe14 start + 52

**Comment by cdelargy** [comment]
Additional info:

- I was able to unblock the issue by removing the proposal from iOS copay wallet.
- After attempting to create a new proposal, the issue did not return.
- Assuming that this means copay created a malformed proposal which was uncaught during parsing.

**Comment by jonasschnelli** [comment]
I could locate the issue,
... during payment proposal parsing we use a 32bit integer (instead of 64bit) for amounts.

A fix is on the way.
