### ISSUE TITLE
Linux v2.2.2 sha256 checksums do not match when downloaded from Chrome

### ISSUE THREAD

**Issue by jonathancross** [digitalbitbox/dbb-app#292]
**UPDATE:** This issue does not appear when downloading through curl or firefox, only Chrome.
I suspect it has to do with the webserver's configured MIME types.
The server's response indicates `Content-Type: application/octet-stream` and `Content-Encoding: gzip`, so I think Chrome may be unzipping the file automatically (thinking it was gzipped by the webserver) resulting in a `.tar.gz` file name that is actual the unzipped tar file.

Possible fix: I checked another web server that works fine for Chrome + `.tar.gz` files (see [Electrum download link](https://download.electrum.org/2.9.3/Electrum-2.9.3.tar.gz)).  Server response indicates a different MIME type: `Content-Type: application/x-gzip` and resulting file is indeed a `.tar.gz`.

-------------------------------------

The sha256 checksums listed on https://digitalbitbox.com/start_linux do not match actual files:

1. [DigitalBitbox_2.2.2_Linux64.tar.gz](https://digitalbitbox.com/download/DigitalBitbox_2.2.2_Linux64.tar.gz)
    - Website: `7b9ac7628a2d9b42d44d05580762d267086c4f82b6bc2ff85257db77aab9b057`
    - Actual: `f5b510a3db38dcb03195b6f4e224feeb64f23648799e88c4f2ada45830d8ee22`

2. [DigitalBitbox_2.2.2_Linux32.tar.gz](https://digitalbitbox.com/download/DigitalBitbox_2.2.2_Linux32.tar.gz)
    - Website: `7f9b096125cd5c546e6f503f82a46c55cf676d090a496540fb1a4cd847e59bcf`
    - Actual: `42693e186627af94c1ecefa436346404b7369fbb9eb5cae4ddc6f1ef945e3642`

**Comment by douglasbakkum** [comment]
Thanks for the hint! I believe this now fixed the problem.

**Comment by jonathancross** [comment]
Works now, thanks!
However I think there might be some more cleanup you'd want to consider.

I noticed that the headers now look like this:

    HTTP/1.1 200 OK
    Server: nginx
    Date: Sun, 22 Oct 2017 15:11:37 GMT
    Content-Type: application/octet-stream
    Content-Length: 11120694
    Last-Modified: Fri, 20 Oct 2017 11:44:57 GMT
    Connection: keep-alive
    ETag: "59e9e1b9-a9b036"
    Content-Type:: application/x-gzip
    Accept-Ranges: bytes

1. We now have an extra colon in `Content-Type:: application/x-gzip`
2. `Content-Type:` is specified twice now.
3. I saw that `Content-Encoding: gzip` was removed (payload no longer compressed in transit), which probably is what really solved the problem.  Correct?

**Comment by douglasbakkum** [comment]
Thanks a lot again. Indeed, appears point 3 was the issue. Now is:

```
 HTTP/1.1 200 OK
 Server: nginx
 Date: Mon, 23 Oct 2017 03:46:08 GMT
 Content-Type: application/x-gzip
 Content-Length: 11120694
 Last-Modified: Fri, 20 Oct 2017 11:44:57 GMT
 Connection: keep-alive
 ETag: "59e9e1b9-a9b036"
 Accept-Ranges: bytes
```
