### ISSUE TITLE
add signmessage functionality on dbb-app cli

### ISSUE THREAD

**Issue by renlord** [digitalbitbox/dbb-app#294]
Right now the signing interface for the dbb-app is very difficult to use due to some intricacies with byte encoding of messages to be signed. It is simply inaccessible to the laymen. It'd be great if there was a convenient wrapper `signmessage` function that takes a message and an address as input arguments, then output the signature for some bitcoin address.

**Comment by srile86** [comment]
Using the little knowledge I have I followed the following steps;
1. cat message.txt | openssl dgst -sha256 | openssl dgst -sha256
2../dbb-cli -password=[password] sign -hasharray='[{"hash": "[output from sha256 x2 of mesage]", "keypath":"m/44'/0'/0'/0/0"}]' <- ran this twice to get output. 

The output result doesn't appear to be a valid signature. Please let me know if this is the right process.

**Comment by jonasschnelli** [comment]
The output is a hex encoded compact signature.
Bitcoin-Core (if you try to verify there) requires a base64 encoded compact signature.

I'm working on a pull request to add this functionality.

**Comment by srile86** [comment]
ok cool, I tried converting the hex encoded the compact signature to base64 but this isn't a valid signature either. 

I'm creating my hash by doing the following
`cat message.txt | openssl dgst -sha256 | openssl dgst -sha256`

Is there a work around while we wait for the PR?

**Comment by srile86** [comment]
@jonasschnelli any chance you can provide a workaround?

**Comment by jonasschnelli** [comment]
I'm working on it... a solution will be ready soon.

**Comment by jonasschnelli** [comment]
See #297

**Comment by renlord** [comment]
Thanks @jonasschnelli
