### ISSUE TITLE
Translating interface

### ISSUE THREAD

**Issue by kizule** [digitalbitbox/dbb-app#296]
Hi, can interface be translated? And if can, how?

**Comment by benma** [comment]
Mi smo u procesu rekonstrukcije naše desktop aplikacije, koja podržava više jezika. Nakon što se oslobodi, može se početi za prevodom. Stay tuned :heart:

**Comment by kizule** [comment]
Okej, hvala puno na odgovoru..

Ok, thank you much on reply.
