### ISSUE TITLE
Join Copay Wallet - Wallet Invitation Code after restored Backup

### ISSUE THREAD

**Issue by eminogrande** [digitalbitbox/dbb-app#300]
Hi,

i've restored my digital bitbox - everything worked fine. I was using it together with a copay multisig. After restoring the device, the digital bitbox app asks me for the Wallet Invitation Code which i can not find in my copay app as it was only showing once during initial creation of the multisig wallet (in copay). Something i'm missing here?

Thanks
Emin

**Comment by benma** [comment]
Hi

If you are asked for the Wallet Invitation Code, it means there is no multisig account associated with that wallet. Please make sure to restore the wallet you used originally in the multisig setup. Also double check the password during backup restoration - it should be the one which was used when you initialized that wallet.

**Comment by eminogrande** [comment]
Ah - this is interesting i didn't know that i have to use the exact same password when restoring the device. I was just playing around with it. Thank you - i will try to restore it again with my "old" password and post here if it was successful.

Edit: that worked fine. Thank you!
